GET http://localhost:5000/api/v1/customer/gr

###
POST http://localhost:5000/driver/login
Content-Type: application/json

{
    "phone": "0335539612",
    "password": "12345678"
}


###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "phone" : "0335539676",
    "password" : "12345678"
}

###
GET http://localhost:5000/order/driver
Content-Type: application/json

{
    "driver_id" : "1"
}

###
PUT http://localhost:5000/driver
Content-Type: application/json

{
    "id" : "1",
    "name" : "Pham van tai"
}